# mkdocs.yml
site_name: Dinámica Molécular

theme:
  name: "material"

plugins:
  - mkdocstrings
markdown_extensions:
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
nav:
  -  index.md
  - explanation.md
  - tutorials.md
  - reference.md


